In [5]:
import numpy as np
from scipy.linalg import svd
from sklearn.decomposition import PCA

In [6]:
# PCA
# 예제 데이터 생성
np.random.seed(0)
data = np.random.randn(5, 3)

# PCA 수행
pca = PCA(n_components=2)
pca.fit(data)
transformed_data = pca.transform(data)

# 결과 출력
print("Original Data:")
print(data)
print("\nPrincipal Components:")
print(pca.components_)
print("\nExplained Variance:")
print(pca.explained_variance_)
print("\nTransformed Data:")
print(transformed_data)

# 역변환하여 원본 데이터 복원
reconstructed_data = pca.inverse_transform(transformed_data)
print("\nReconstructed Data:")
print(reconstructed_data)


Original Data:
[[ 1.76405235  0.40015721  0.97873798]
 [ 2.2408932   1.86755799 -0.97727788]
 [ 0.95008842 -0.15135721 -0.10321885]
 [ 0.4105985   0.14404357  1.45427351]
 [ 0.76103773  0.12167502  0.44386323]]

Principal Components:
[[ 0.51356804  0.55749392 -0.65226405]
 [-0.46282974 -0.46011835 -0.75768049]]

Explained Variance:
[1.68684967 0.3132443 ]

Transformed Data:
[[-0.16989797 -0.68360167]
 [ 2.1688981  -0.09744077]
 [-0.18966821  0.76666454]
 [-1.31794514 -0.29964437]
 [-0.49138678  0.31402227]]

Reconstructed Data:
[[ 1.45447105  0.6962359   0.98804559]
 [ 2.38430928  1.7303971  -0.9815897 ]
 [ 0.77309135  0.01792001 -0.09789741]
 [ 0.68716386 -0.1204592   1.44595853]
 [ 0.82763464  0.05798277  0.44186099]]


In [7]:
# SVD
# 예제 데이터 생성
np.random.seed(0)
data = np.random.randn(5, 3)

# SVD 수행
U, S, VT = svd(data)

# 결과 출력
print("Original Data:")
print(data)
print("\nU matrix:")
print(U)
print("\nSingular values:")
print(S)
print("\nVT matrix:")
print(VT)

# 재구성된 데이터 확인 (U * S * VT)
S_matrix = np.zeros((U.shape[0], VT.shape[0]))
np.fill_diagonal(S_matrix, S)
reconstructed_data = np.dot(U, np.dot(S_matrix, VT))
print("\nReconstructed Data:")
print(reconstructed_data)


Original Data:
[[ 1.76405235  0.40015721  0.97873798]
 [ 2.2408932   1.86755799 -0.97727788]
 [ 0.95008842 -0.15135721 -0.10321885]
 [ 0.4105985   0.14404357  1.45427351]
 [ 0.76103773  0.12167502  0.44386323]]

U matrix:
[[-0.48210141 -0.52904292 -0.21861646 -0.559567   -0.35606661]
 [-0.81822219  0.47275608  0.29815135  0.13410847  0.01161116]
 [-0.21411045 -0.05028782 -0.77030394  0.59144894 -0.0919121 ]
 [-0.10926226 -0.65923749  0.50011465  0.54912565 -0.04259167]
 [-0.20077137 -0.24391053 -0.1408183  -0.13247208  0.92888098]]

Singular values:
[3.53789464 2.14896553 0.76883707]

VT matrix:
[[-0.87201072 -0.48863919  0.02879325]
 [-0.17587459  0.25787931 -0.95003494]
 [-0.45679912  0.83350465  0.31081274]]

Reconstructed Data:
[[ 1.76405235  0.40015721  0.97873798]
 [ 2.2408932   1.86755799 -0.97727788]
 [ 0.95008842 -0.15135721 -0.10321885]
 [ 0.4105985   0.14404357  1.45427351]
 [ 0.76103773  0.12167502  0.44386323]]
