## 텐서플로우 시작하기

In [ ]:
import numpy as np
import tensorflow as tf

In [ ]:
print(tf.__version__)

2.15.0


### 텐서(Tensor)의 객체
- 타입(Type): `string`, `float32`, `float16`, `int32`, `int8` 등

- 형상(Shape): 0, 1, 2차원 등의 데이터 차원

- 축(Rank): 차원의 개수

### 텐서의 차원과 연산

In [ ]:
a = tf.constant(2)
print(tf.rank(a))
print(a)

tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)


In [ ]:
b  = tf.constant([2,3])
print(tf.rank(b))
print(b)

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor([2 3], shape=(2,), dtype=int32)


In [ ]:
c = tf.constant([[2,3],[6,7]])
print(tf.rank(c))
print(c)

tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(
[[2 3]
 [6 7]], shape=(2, 2), dtype=int32)


In [ ]:
d = tf.constant(['hello'])
print(tf.rank(d))
print(d)

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor([b'hello'], shape=(1,), dtype=string)


### 난수 생성

In [ ]:
rand1 = tf.random.uniform([1],0,1)
print(rand1.shape)
print(rand1)

(1,)
tf.Tensor([0.9940796], shape=(1,), dtype=float32)


In [ ]:
rand2 = tf.random.normal([1,2],0,1)
print(rand2.shape)
print(rand2)

(1, 2)
tf.Tensor([[ 0.4728844 -0.9251015]], shape=(1, 2), dtype=float32)


In [ ]:
rand3 = tf.random.normal(shape=(3,2), mean=0, stddev=1)
print(rand3.shape)
print(rand3)

(3, 2)
tf.Tensor(
[[-0.434094    0.77111846]
 [ 0.7342491   0.14359157]
 [-0.17524889  1.1800925 ]], shape=(3, 2), dtype=float32)


### 즉시 실행 모드 (Eager Mode) 지원
- 즉시 실행모드를 통해 텐서플로우를 파이썬처럼 사용할 수 있음

- 1.x 버전에서는 '그래프'를 생성하고, 초기화 한 뒤에 세션을 통해 **값을 흐르게 하는 작업**을 진행해야함


In [ ]:
a = tf.constant(3)
b = tf.constant(2)

In [ ]:
print(tf.add(a,b))
print(a+b)

tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(5, shape=(), dtype=int32)


In [ ]:
print(tf.subtract(a,b))
print(a-b)

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)


In [ ]:
print(tf.multiply(a,b))
print(a*b)

tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)


### 텐서 플로우 ↔ 넘파이
- `numpy()`
- `tf.convet_to_tensor()`

In [ ]:
c = (a+b).numpy()
print(c)
print(type(c))

5
<class 'numpy.int32'>


In [ ]:
[1,2,3]
(1,2,3)

In [ ]:
c_sqrt = np.sqrt(c,dtype=np.float32)
c_tensor = tf.convert_to_tensor(c_sqrt)

print(c_tensor)
print(type(c_tensor))

tf.Tensor(2.236068, shape=(), dtype=float32)
<class 'tensorflow.python.framework.ops.EagerTensor'>


### 넘파이처럼 사용하기


In [ ]:
t = tf.constant([[1.,2.,3.],[4.,5.,6.]])
print(t.shape)
print(t.dtype)

(2, 3)
<dtype: 'float32'>


In [ ]:
print(t[:,1:])

tf.Tensor(
[[2. 3.]
 [5. 6.]], shape=(2, 2), dtype=float32)


In [ ]:
t + 10

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[11., 12., 13.],
       [14., 15., 16.]], dtype=float32)>

In [ ]:
tf.square(t)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 1.,  4.,  9.],
       [16., 25., 36.]], dtype=float32)>

In [ ]:
t @ tf.transpose(t)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[14., 32.],
       [32., 77.]], dtype=float32)>

### 타입 변환
- 텐서의 기본 dtype
  - float형 텐서: `float32`
  - int형 텐서: `int32`

- 연산시 텐서의 타입을 맞춰줘야 함
  - `float32` ~ `float32`
  - `int32` ~ `int32`
  - `flot32` ~ `int32` (x)

- 타입변환에는 `tf.cast()` 사용

In [ ]:
a = tf.constant(2)
print(a)

b = tf.constant(2.)
print(b)

tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(2.0, shape=(), dtype=float32)


In [ ]:
a+b

InvalidArgumentError: cannot compute AddV2 as input #1(zero-based) was expected to be a int32 tensor but is a float tensor [Op:AddV2] name: 

In [ ]:
tf.constant(2.) + tf.constant(2., dtype=tf.float64)

InvalidArgumentError: cannot compute AddV2 as input #1(zero-based) was expected to be a float tensor but is a double tensor [Op:AddV2] name: 

In [ ]:
t = tf.constant(2.0, dtype=tf.float64) # float64
t2 = tf.constant(2.)                   # float32

t3 = t + tf.cast(t2, tf.float64)
print(t3)
print(type(t3))

tf.Tensor(4.0, shape=(), dtype=float64)
<class 'tensorflow.python.framework.ops.EagerTensor'>


In [ ]:
t = tf.constant(2, )
t2 = tf.constant(2.)

t3 = t + tf.cast(t2, tf.int32)
print(t3)
print(type(t3))

tf.Tensor(4, shape=(), dtype=int32)
<class 'tensorflow.python.framework.ops.EagerTensor'>


In [ ]:
t = tf.constant(2, )
t2 = tf.constant(2.)

t3 = t2 + tf.cast(t, tf.float32)
print(t3)
print(type(t3))

tf.Tensor(4.0, shape=(), dtype=float32)
<class 'tensorflow.python.framework.ops.EagerTensor'>


### AutoGraph (오토그래프)

- Tensorflow가 작업을 좀 더 빠르게 동작하게 하기 위한 방법으로 Graph로 만들어 연산을 진행

- `tf.Graph`

- 유연성이 있음

  - 모바일 애플리케이션, 임베디드 기기, 백엔드 서버와 같이 Python 인터프리터가 없는 환경에서 Tensorflow 사용 가능

In [ ]:
import timeit

### @tf.function
- 자동으로 그래프를 생성(Auto Graph)

- 그래프로 변환하여 사용 -> GPU 연산 가능

- 파이썬으로 구성된 함수를 텐서플로우의 그래프 형태로 다루고 싶을 때 사용가능


- 원본 함수가 필요하다면 `(tf.function).python_function()`

In [ ]:
@tf.function
def my_function(x):
  return x**2 - 10*x + 3

print(my_function(2))
print(my_function(tf.constant(2)))

tf.Tensor(-13, shape=(), dtype=int32)
tf.Tensor(-13, shape=(), dtype=int32)


In [ ]:
def my_func(x):
  return x**2 - 10*x + 3

print(my_func(2))
print(my_func(tf.constant(2)))

-13
tf.Tensor(-13, shape=(), dtype=int32)


In [ ]:
tf_my_func = tf.function(my_func)
print(tf_my_func(2))
print(tf_my_func.python_function(2))

tf.Tensor(-13, shape=(), dtype=int32)
-13


In [ ]:
def function_to_get_faster(x,y,b):
  x = tf.matmul(x,y)
  x = x + b
  return x

a_function_that_uses_a_graph = tf.function(function_to_get_faster)

x1 = tf.constant([[1. , 2.]])
y1 = tf.constant([[2.], [3.]])
b1 = tf.constant(4.)

print(x1.shape)
print(y1.shape)

a_function_that_uses_a_graph(x1,y1,b1).numpy()

(1, 2)
(2, 1)


array([[12.]], dtype=float32)

In [ ]:
def inner_function(x,y,b):
  x = tf.matmul(x,y)
  x = x + b
  return x

@tf.function
def outer_function(x):
  y = tf.constant([[2.], [3.]])
  b = tf.constant(4.)
  return inner_function(x,y,b)

outer_function(tf.constant([[1. , 2.]])).numpy()

array([[12.]], dtype=float32)

텐서플로우가 `tf.function`으로 변환한 코드

In [ ]:
print(tf.autograph.to_code(my_function.python_function))

def tf__my_function(x):
    with ag__.FunctionScope('my_function', 'fscope', ag__.ConversionOptions(recursive=True, user_requested=True, optional_features=(), internal_convert_user_code=True)) as fscope:
        do_return = False
        retval_ = ag__.UndefinedReturnValue()
        try:
            do_return = True
            retval_ = ag__.ld(x) ** 2 - 10 * ag__.ld(x) + 3
        except:
            do_return = False
            raise
        return fscope.ret(retval_, do_return)




 속도 향상


In [ ]:
class SequentialModel(tf.keras.Model):
  def __init__(self, **kwargs):
    super(SequentialModel, self).__init__(**kwargs)
    self.flatten = tf.keras.layers.Flatten(input_shape=(28,28))
    self.dense_1 = tf.keras.layers.Dense(128, activation = 'relu')
    self.dropout = tf.keras.layers.Dropout(0.2)
    self.dense_2 = tf.keras.layers.Dense(10)

  def call(self,x):
    x = self.flatten(x)
    x = self.dense_1(x)
    x = self.dropout(x)
    x = self.dense_2(x)
    return x

input_data = tf.random.uniform([60,28,28])

eager_model = SequentialModel()
graph_model = tf.function(eager_model)

print(f"Eager time: {timeit.timeit(lambda: eager_model(input_data), number = 10000)}")
print(f"Graph time: {timeit.timeit(lambda: graph_model(input_data), number = 10000)}")

Eager time: 20.249131743000135
Graph time: 6.238645463000012


### 변수 생성

- `tf.Variable`
- 딥러닝 모델 학습 시, 그래프 연산이 필요할 때 사용

In [ ]:
X = tf.Variable(20.)

print(X)

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=20.0>


### Autograd (자동 미분)

- `tf.GradientTape` API를 사용
- `tf.Variable` 같은 일부 입력에 대한 기울기 계산
  - 기본적으로 한번만 사용됨
- 변수가 포함된 연산만 기록

In [ ]:
x = tf.Variable(3.)
with tf.GradientTape() as tape:
  y = x**2

In [ ]:
print(type(x))
print(type(y))

<class 'tensorflow.python.ops.resource_variable_ops.ResourceVariable'>
<class 'tensorflow.python.framework.ops.EagerTensor'>


In [ ]:
dy_dx = tape.gradient(y,x)
dy_dx.numpy()

6.0

In [ ]:
x2 = tf.Variable(4)
dy_dx = tape.gradient(y,x2)
dy_dx.numpy()

RuntimeError: A non-persistent GradientTape can only be used to compute one set of gradients (or jacobians)

In [ ]:
x = tf.Variable(2.)
y = tf.Variable(3.)

with tf.GradientTape() as tape:
  y_sq = y**2
  z = x**2 + tf.stop_gradient(y_sq)

In [ ]:
grad = tape.gradient(z,{'x':x, 'y':y})
print('dz/dx: ', grad['x'])
print('dz/dy: ', grad['y'])

dz/dx:  tf.Tensor(4.0, shape=(), dtype=float32)
dz/dy:  None


In [ ]:
weights = tf.Variable(tf.random.normal((3,2)), name ="wieghts")
biases = tf.Variable(tf.zeros(2, dtype=tf.float32), name = "biases")

x = [[1., 2., 3.]]

with tf.GradientTape(persistent=True) as tape:
  y = x @ weights + biases
  loss = tf.reduce_mean(y**2)

In [ ]:
[dl_dw, dl_db] = tape.gradient(loss, [weights, biases])

In [ ]:
print(weights.shape)
print(dl_dw.shape)
print(weights)
print(dl_dw)

(3, 2)
(3, 2)
<tf.Variable 'wieghts:0' shape=(3, 2) dtype=float32, numpy=
array([[ 1.1567245 , -0.18265818],
       [-1.5220158 , -0.3949808 ],
       [ 0.421589  , -0.32500663]], dtype=float32)>
tf.Tensor(
[[-0.62254024 -1.9476397 ]
 [-1.2450805  -3.8952794 ]
 [-1.8676207  -5.8429193 ]], shape=(3, 2), dtype=float32)


In [ ]:
weights2 = tf.Variable(tf.random.normal((3,2)), name ="wieghts")
biases2 = tf.Variable(tf.zeros(2, dtype=tf.float32), name = "biases")
x2 = [[4., 5., 6.]]

[dl_dw2, dl_db2] = tape.gradient(loss, [weights2, biases2])

print(weights2.shape)
print(dl_dw.shape)
print(weights2)
print(dl_dw)

(3, 2)
(3, 2)
<tf.Variable 'wieghts:0' shape=(3, 2) dtype=float32, numpy=
array([[ 0.49038503,  0.06234931],
       [ 0.07925958,  0.5294223 ],
       [-1.4568152 , -0.5420338 ]], dtype=float32)>
tf.Tensor(
[[-0.62254024 -1.9476397 ]
 [-1.2450805  -3.8952794 ]
 [-1.8676207  -5.8429193 ]], shape=(3, 2), dtype=float32)
